
/* Question 1*/
SELECT P.PS_ID,PS_TASK,PS_BEGINDATE,PS_ENDDATE,SKILL_DESCRIPTION, ES.EMP_LNAME,ES.EMP_FNAME,ASN_BEGINDATE,ASN_ENDDATE
FROM EMPSKILL AS ES JOIN EMPLOYEE AS E ON ES.EMP_ID = E.EMP_ID
JOIN ASN AS A ON A.EMP_ID = E.EMP_ID
JOIN PS AS P ON P.PS_ID = A.PS_ID
ORDER BY PS_BEGINDATE, PS_ENDDATE;


/* Question 2*/
SELECT PS_ID,PS_BEGINDATE,PS_ENDDATE,PS_TASK,SKILL_DESCRIPTION,PS_QTY
FROM PS AS P JOIN SKILL AS S ON P.SKILL_ID = S.SKILL_ID
ORDER BY PS_BEGINDATE, PS_ENDDATE;

/* Question 3*/
SELECT REGION_NAME,SKILL_DESCRIPTION,ES.EMP_LNAME,ES.EMP_FNAME,EMP_HIREDATE
FROM EMPSKILL AS ES JOIN EMPLOYEE AS E ON ES.EMP_ID = E.EMP_ID
JOIN REGION AS R ON R.REGION_ID = E.REGION_ID
ORDER BY REGION_NAME, SKILL_DESCRIPTION, EMP_HIREDATE;

/* Question 4*/
SELECT distinct PS_TASK,S.SKILL_DESCRIPTION,ES.EMP_LNAME,ES.EMP_FNAME
FROM PS AS P JOIN SKILL AS S ON P.SKILL_ID = S.SKILL_ID
JOIN EMPSKILL AS ES ON ES.SKILL_ID = S.SKILL_ID
JOIN EMPLOYEE AS E ON ES.EMP_ID = E.EMP_ID
JOIN ASN AS A ON A.EMP_ID = E.EMP_ID
WHERE PS_BEGINDATE >= '2018-06-10';

/* Question 5*/

SELECT R.REGION_NAME,S.SKILL_DESCRIPTION,COUNT(E.EMP_ID) AS 'Count'
FROM REGION AS R INNER JOIN EMPLOYEE AS E ON R.REGION_ID = E.REGION_ID
INNER JOIN EMPSKILL AS ES ON ES.EMP_ID = E.EMP_ID
INNER JOIN SKILL AS S ON S.SKILL_ID = ES.SKILL_ID
GROUP BY R.REGION_NAME , S.SKILL_DESCRIPTION
ORDER BY R.REGION_NAME , S.SKILL_DESCRIPTION;

/* Question 6 */

SELECT ES.SKILL_DESCRIPTION , (WL_HOURS) AS Hours , SKILL_RATE , ROUND((WL_HOURS * SKILL_RATE),2) AS 'Total'
FROM WORKLOG AS W JOIN ASN AS A ON W.ASN_ID = A.ASN_ID
JOIN EMPLOYEE AS E ON E.EMP_ID = A.EMP_ID
JOIN EMPSKILL AS ES ON ES.EMP_ID = E.EMP_ID
JOIN SKILL AS S ON S.SKILL_ID = ES.SKILL_ID
ORDER BY ES.SKILL_DESCRIPTION, SKILL_RATE;


/* Question 7 */

SELECT PRJ_DESCRIPTION, SUM(WL_HOURS) AS 'Total Hours', SUM(WL_HOURS) AS 'Total Billed'
FROM PROJECT AS P JOIN BILL AS B ON P.PRJ_ID = B.PRJ_ID
JOIN WORKLOG AS W ON W.BILL_ID = B.BILL_ID
GROUP BY PRJ_DESCRIPTION;

/* Question 8*/

SELECT distinct ES.EMP_LNAME,  ES.EMP_FNAME, ES.SKILL_DESCRIPTION, SKILL_RATE, ROUND((WL_HOURS),0) AS 'TOTAL_HOURS', ROUND((SKILL_RATE * WL_HOURS),0) AS 'TOTAL'
FROM SKILL AS S JOIN EMPSKILL AS ES ON S.SKILL_ID = ES.SKILL_ID
JOIN EMPLOYEE AS E ON E.EMP_ID = ES.EMP_ID
JOIN ASN AS A ON A.EMP_ID = E.EMP_ID
JOIN WORKLOG AS W ON W.ASN_ID = A.ASN_ID
ORDER BY EMP_LNAME, EMP_FNAME, SKILL_DESCRIPTION, SKILL_RATE;

/* Question 9 */

SELECT S.SKILL_ID,S.SKILL_DESCRIPTION,E.EMP_LNAME,E.EMP_FNAME
FROM SKILL AS S INNER JOIN EMPSKILL AS ES ON S.SKILL_ID = ES.SKILL_ID
INNER JOIN EMPLOYEE AS E ON E.EMP_ID = ES.EMP_ID
ORDER BY S.SKILL_ID , E.EMP_LNAME ASC;

/* Question 10 */

SELECT DISTINCT E.EMP_LNAME, E.EMP_FNAME, W.WL_DATE, A.ASN_ID, P.PS_TASK, S.SKILL_DESCRIPTION, W.WL_HOURS, W.BILL_ID
FROM WORKLOG AS W JOIN ASN AS A ON W.ASN_ID = A.ASN_ID
JOIN EMPLOYEE AS E ON E.EMP_ID = A.EMP_ID
JOIN EMPSKILL AS ES ON ES.EMP_ID = E.EMP_ID
JOIN SKILL AS S ON S.SKILL_ID = ES.SKILL_ID
JOIN PS AS P ON P.SKILL_ID = S.SKILL_ID
ORDER BY A.ASN_ID, W.WL_DATE, E.EMP_LNAME, E.EMP_FNAME;

/* Question 11 */

SELECT E.EMP_LNAME, E.EMP_FNAME, P.PS_TASK, S.SKILL_DESCRIPTION, SUM(W.WL_HOURS) AS 'SumOfWL_Hours', S.SKILL_RATE, ROUND(SUM(W.WL_HOURS * S.SKILL_RATE),2) AS 'TOTAL'
FROM WORKLOG AS W JOIN ASN AS A ON W.ASN_ID = A.ASN_ID
JOIN EMPLOYEE AS E ON E.EMP_ID = A.EMP_ID
JOIN EMPSKILL AS ES ON ES.EMP_ID = E.EMP_ID
JOIN SKILL AS S ON S.SKILL_ID = ES.SKILL_ID
JOIN PS AS P ON P.SKILL_ID = S.SKILL_ID	
GROUP BY E.EMP_LNAME, E.EMP_FNAME, P.PS_TASK, S.SKILL_DESCRIPTION, S.SKILL_RATE, A.ASN_ID
ORDER BY A.ASN_ID;












